# Generated by Django 4.0.6 on 2022-07-19 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_category', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='CloudMessagingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm_token', models.CharField(max_length=255)),
                ('cm_ip', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_image', models.CharField(default='image', max_length=255)),
                ('image', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_tag', models.CharField(max_length=255, unique=True)),
                ('tag_slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_subcategory', models.CharField(max_length=255, unique=True)),
                ('subcategory_slug', models.SlugField(max_length=255, unique=True)),
                ('article_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.articlecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=255)),
                ('article_header_image_url', models.CharField(max_length=255)),
                ('article_description', models.TextField()),
                ('article_title', models.CharField(max_length=255)),
                ('article_content', models.TextField()),
                ('article_published', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('article_slug', models.SlugField(max_length=255, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('article_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.articlesubcategory', verbose_name='Sub Category')),
                ('article_tags', models.ManyToManyField(to='magazine.tag')),
            ],
        ),
    ]
