# Generated by Django 4.0.6 on 2022-07-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_alter_article_article_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
